### ISSUE TITLE
I can't find amr-models

### ISSUE THREAD

**Issue by ckj18** [zzshou/amr-data-augmentation#3]
sample.txt is a file
Some weights of AMRBartForConditionalGeneration were not initialized from the model checkpoint at facebook/bart-large and are newly initialized: ['decoder.pointer_k.weight', 'decoder.pointer_k.bias', 'decoder.pointer_q.weight', 'decoder.pointer_q.bias', 'final_logits_bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "bin/predict_amrs_from_plaintext.py", line 98, in <module>
    model.load_state_dict(torch.load(args.checkpoint, map_location='cpu')['model'])
  File "/home/ckjwh/anaconda3/envs/AMR/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ckjwh/anaconda3/envs/AMR/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ckjwh/anaconda3/envs/AMR/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'amr-models/AMR2.parsing.pt'

I execute 'bash predict_amr.sh sample.txt, but this error occured.

**Comment by zzshou** [comment]
The parsing model can be downloaded from [link](http://nlp.uniroma1.it/AMR/AMR2.parsing-1.0.tar.bz2) from [SPRING](https://github.com/SapienzaNLP/spring).
